### PR TITLE
A redesign of my theme

### PR DESCRIPTION
**Pull request by olvlvl**
Hi,

I redesigned my bootstrap theme, improving search suggestions, sidebar overflow, legibility, and I also replaced the bootstrap v3 styles with a selection of v4 (I removed the big bootstrap file).

Biggest changes:

- Removed all panels and most tables. The _class_ view is the most impacted. I replaced the table columns by a flat view with: name, type, attributes. Now it displays fine on smaller screens.
- Search suggestions are displayed full screen, under the search input.
- If the menu inside the sidebar overflows, it is shown entirely when the mouse hovers, making it more readable. I removed the splitter since it's of no use anymore.
- Replaced some PNG files with glyphs, added a SVG icon for the link.
- New behavior for the search button
- The theme is now responsive, you can check your documentation from your phone.

You can see it in action over here: <https://olvlvl.com/apigen/class-ApiGen.Parser.Reflection.ReflectionElement.html>

Feedback appreciated <3

### CODE REVIEW

**Comment by jankal** [comment]
This may be shipped with the next version of apigen.
@olvlvl You may merge it yourself.

**Comment by jankal** [comment]
@olvlvl I'm concerned of how the user is able to open up the source. I tried in your demo but I wasn't able to open up the source of a specific method.

**Comment by olvlvl** [comment]
I have to look into this because I'm generating my docs without sources.

**Comment by jankal** [comment]
You don't? @kukulich

**Comment by TomasVotruba** [comment]
Hi @olvlvl ,

thank you for great work!

We are merging themes to main ApiGen\ApiGen repository, already did for [DefaultTheme](https://github.com/ApiGen/ApiGen/tree/master/packages/ThemeDefault/src), so it's easier to develop.

Could you send PR there after you finish it here? I'll take care about the changes in v5, don't worry about them.

**Comment by TomasVotruba** [comment]
Can I add this?

**Comment by olvlvl** [comment]
Hi Tomas, give me a sec, I'll do it.

**Comment by olvlvl** [comment]
Here: https://github.com/ApiGen/ApiGen/pull/840

**Comment by TomasVotruba** [comment]
Awesome job. Thank you!

**Pull request merged**
